name: Airflow Workflow

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test DAGs with Pytest
      run: |
        pip install pytest
        pip install apache-airflow
        pytest test_dag_validation.py